#!/usr/bin/env python3
"""Run the three MPEX scenario-14 resonance-placement comparison cases.

The three cases are the left and right 70 GHz second-harmonic resonance
crossings around the magnetic well, plus the magnetic-well minimum between
them.  Each case is run through the Fortran reference and PICOS++ input decks
generated by compare_mpex_scenario14_fig17.py.
"""

from __future__ import annotations

import argparse
import csv
import math
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Case:
    tag: str
    title: str
    case_token: str
    rf_frequency_hz: float
    resonance_b_t: float
    resonance_z_m: float


CASES = (
    Case(
        tag="left_resonance_70ghz",
        title="70 GHz left resonance",
        case_token="70GHz_LeftRes",
        rf_frequency_hz=7.0e10,
        resonance_b_t=1.2503353635073735,
        resonance_z_m=2.705440369,
    ),
    Case(
        tag="right_resonance_70ghz",
        title="70 GHz right resonance",
        case_token="70GHz_RightRes",
        rf_frequency_hz=7.0e10,
        resonance_b_t=1.2503353635073735,
        resonance_z_m=3.119647187,
    ),
    Case(
        tag="well_min_65p588ghz",
        title="magnetic-well minimum",
        case_token="WellMin_65p588GHz",
        rf_frequency_hz=6.5587790285535164e10,
        resonance_b_t=1.171524765833,
        resonance_z_m=2.874371859,
    ),
)


def run_label(args: argparse.Namespace) -> str:
    if args.run_label:
        return args.run_label
    time_ns = args.physical_time * 1.0e9
    if math.isclose(time_ns, round(time_ns), rel_tol=0.0, abs_tol=1.0e-9):
        time_token = f"{int(round(time_ns))}ns"
    else:
        time_token = f"{time_ns:.4g}ns".replace(".", "p")
    coll_token = "coll" if args.collisions else "nocoll"
    return f"p{args.particles}_{time_token}_{coll_token}"


def case_names(case: Case, label: str) -> tuple[str, str, str, str]:
    fortran_case = f"xp_MPEX_Scenario14_Ex8_{case.case_token}_Target8_{label}"
    descriptor = f"ex8_{case.tag}_target8_{label}"
    picos_base = f"mpex_scenario14_ex8_{case.tag}_target8_{label}"
    return fortran_case, descriptor, f"{picos_base}_nonrel", f"{picos_base}_rel"


def compare_command(args: argparse.Namespace, case: Case, out_dir: Path, smooth: bool) -> list[str]:
    label = run_label(args)
    case_name, descriptor, picos_nonrel, picos_rel = case_names(case, label)
    command = [
        sys.executable,
        str(args.picos_root / "scripts" / "compare_mpex_scenario14_fig17.py"),
        "--plot",
        "--linear-root",
        str(args.linear_root),
        "--picos-build-dir",
        str(args.picos_build_dir),
        "--scenario14-b-file",
        str(args.scenario14_b_file),
        "--b-scale",
        f"{args.b_scale:.16e}",
        f"--z-min={args.z_min:.16e}",
        f"--z-max={args.z_max:.16e}",
        f"--plot-z-min={args.plot_z_min:.16e}",
        f"--plot-z-max={args.plot_z_max:.16e}",
        "--energy-max",
        f"{args.energy_max:.16e}",
        "--rf-frequency",
        f"{case.rf_frequency_hz:.16e}",
        "--no-derive-rf-frequency-from-resonance-b",
        "--resonance-b-t",
        f"{case.resonance_b_t:.16e}",
        "--resonance-z",
        f"{case.resonance_z_m:.16e}",
        "--rf-window-end",
        f"{args.target_z:.16e}",
        "--target-z",
        f"{args.target_z:.16e}",
        "--particles",
        str(args.particles),
        "--steps",
        str(args.steps),
        "--physical-time",
        f"{args.physical_time:.16e}",
        "--output-count",
        str(args.output_count),
        "--collisions",
        str(args.collisions),
        "--omp-threads",
        str(args.omp_threads),
        "--fortran-omp-threads",
        str(args.fortran_omp_threads),
        "--picos-omp-threads",
        str(args.picos_omp_threads),
        "--mpi-ranks",
        str(args.mpi_ranks),
        "--case-name",
        case_name,
        "--descriptor",
        descriptor,
        "--picos-tag-nonrel",
        picos_nonrel,
        "--picos-tag-rel",
        picos_rel,
        "--out-dir",
        str(out_dir),
    ]
    if args.picos_run_mode != "none":
        command.extend(["--picos-run-mode", args.picos_run_mode])
    if smooth:
        command.extend(
            [
                "--smooth-z-bins",
                f"{args.smooth_z_bins:.16e}",
                "--smooth-energy-bins",
                f"{args.smooth_energy_bins:.16e}",
                "--mask-below-log-vmin",
            ]
        )
    else:
        command.append("--setup")
        if not args.setup_only:
            command.append("--run-fortran")
        if not args.setup_only and args.picos_run_mode != "none":
            command.append("--run-picos")
    return command


def run_command(command: list[str], log_path: Path, dry_run: bool) -> None:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    if dry_run:
        print(" ".join(command))
        return
    env = os.environ.copy()
    env["MPLBACKEND"] = "Agg"
    env["HDF5_USE_FILE_LOCKING"] = "FALSE"
    with log_path.open("w") as log:
        log.write(" ".join(command) + "\n\n")
        log.flush()
        subprocess.check_call(command, cwd=Path.cwd(), env=env, stdout=log, stderr=subprocess.STDOUT)


def read_case_metadata(readme_path: Path) -> dict[str, str]:
    metadata: dict[str, str] = {}
    if not readme_path.is_file():
        return metadata
    for line in readme_path.read_text().splitlines():
        if "harmonic resonance field" in line:
            metadata["resonance"] = line.split(": ", 1)[1].strip().rstrip(".")
        elif "Selected resonance marker" in line:
            metadata["resonance_z"] = line.split(": ", 1)[1].strip().rstrip(".")
        elif "RF window" in line:
            metadata["rf_window"] = line.split(": ", 1)[1].strip().rstrip(".")
        elif "Target marker" in line:
            metadata["target"] = line.split(": ", 1)[1].strip().rstrip(".")
    return metadata


def write_combined_summary(args: argparse.Namespace) -> Path:
    out_root = args.out_root.resolve()
    rows: list[dict[str, str]] = []
    label = run_label(args)
    for case in CASES:
        folder = out_root / case.tag
        metadata = read_case_metadata(folder / "README.md")
        csv_path = folder / "scenario14_fig17_summary.csv"
        if not csv_path.is_file():
            continue
        with csv_path.open() as handle:
            for row in csv.DictReader(handle):
                row = dict(row)
                row["case"] = case.title
                row["case_tag"] = case.tag
                row["resonance"] = metadata.get("resonance", "")
                row["resonance_z"] = metadata.get("resonance_z", "")
                row["rf_window"] = metadata.get("rf_window", "")
                row["target"] = metadata.get("target", "")
                rows.append(row)

    summary_csv = out_root / "triplet_summary.csv"
    fieldnames = [
        "case",
        "case_tag",
        "run",
        "has_output",
        "count",
        "mean_energy_eV",
        "p99_energy_eV",
        "max_energy_eV",
        "rf_absorbed_power_W",
        "resonance",
        "resonance_z",
        "rf_window",
        "target",
    ]
    with summary_csv.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore", lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)

    readme = out_root / "README.md"
    lines = [
        "# MPEX Scenario-14 Resonance Triplet",
        "",
        f"- Run label: `{label}`.",
        f"- Domain: `{args.z_min:g}` to `{args.z_max:g}` m.",
        f"- Target: `{args.target_z:g}` m.",
        f"- Particles: `{args.particles}`.",
        f"- Physical time: `{args.physical_time:.4g}` s.",
        f"- Fortran steps: `{args.steps}`.",
        f"- PICOS output intervals: `{args.output_count}` plus the initial snapshot.",
        f"- PICOS++ run mode: `{args.picos_run_mode}`.",
        f"- PICOS++ MPI ranks: `{args.mpi_ranks}`.",
        f"- Fallback OpenMP threads: `{args.omp_threads}`.",
        f"- Fortran OpenMP threads: `{args.fortran_omp_threads}`.",
        f"- PICOS++ OpenMP threads per rank: `{args.picos_omp_threads}`.",
        "",
        "| case | run | output | count | mean E [eV] | P99 [eV] | max E [eV] | RF absorbed [W] |",
        "|---|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        if row.get("has_output") != "True":
            lines.append(f"| {row['case']} | {row['run']} | no |  |  |  |  |  |")
            continue
        lines.append(
            f"| {row['case']} | {row['run']} | yes | {int(row['count'])} | "
            f"{float(row['mean_energy_eV']):.4g} | {float(row['p99_energy_eV']):.4g} | "
            f"{float(row['max_energy_eV']):.4g} | {float(row['rf_absorbed_power_W']):.4g} |"
        )
    lines.append("")
    lines.append(f"Combined CSV: `{summary_csv.name}`.")
    readme.write_text("\n".join(lines) + "\n")
    return readme


def parse_args() -> argparse.Namespace:
    picos_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--picos-root", type=Path, default=picos_root)
    parser.add_argument("--linear-root", type=Path, default=Path("/home/78k/picos_kinetic_electron_eval/LinearFokkerPlanck_Axisymmetric"))
    parser.add_argument("--picos-build-dir", type=Path, default=Path("build-fusiont6"))
    parser.add_argument("--scenario14-b-file", type=Path, default=Path("templateFILES/MPEX_B_norm_PICOS_scenario_14.txt"))
    parser.add_argument("--out-root", type=Path, default=Path("validation/mpex_scenario14_triplet_picos_fortran"))
    parser.add_argument("--run-label", default="")
    parser.add_argument("--particles", type=int, default=65536)
    parser.add_argument("--steps", type=int, default=8000)
    parser.add_argument("--physical-time", type=float, default=1.0e-9)
    parser.add_argument("--output-count", type=int, default=1)
    parser.add_argument("--b-scale", type=float, default=0.200418652427244)
    parser.add_argument("--z-min", type=float, default=-2.0)
    parser.add_argument("--z-max", type=float, default=8.0)
    parser.add_argument("--plot-z-min", type=float, default=-2.0)
    parser.add_argument("--plot-z-max", type=float, default=8.0)
    parser.add_argument("--energy-max", type=float, default=3500.0)
    parser.add_argument("--target-z", type=float, default=8.0)
    parser.add_argument("--collisions", type=int, choices=[0, 1], default=0)
    parser.add_argument("--mpi-ranks", type=int, default=2)
    parser.add_argument("--omp-threads", type=int, default=48)
    parser.add_argument("--fortran-omp-threads", type=int, default=48)
    parser.add_argument("--picos-omp-threads", type=int, default=1)
    parser.add_argument("--smooth-z-bins", type=float, default=0.8)
    parser.add_argument("--smooth-energy-bins", type=float, default=0.8)
    parser.add_argument("--picos-run-mode", choices=["both", "nonrel", "rel", "none"], default="both")
    parser.add_argument("--setup-only", action="store_true", help="Generate Fortran/PICOS input decks and metadata without running either solver.")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--skip-smooth", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    args.picos_root = args.picos_root.resolve()
    if not args.picos_build_dir.is_absolute():
        args.picos_build_dir = args.picos_root / args.picos_build_dir
    if not args.scenario14_b_file.is_absolute():
        args.scenario14_b_file = args.picos_root / args.scenario14_b_file
    if not args.out_root.is_absolute():
        args.out_root = args.picos_root / args.out_root
    args.out_root.mkdir(parents=True, exist_ok=True)

    for case in CASES:
        out_dir = args.out_root / case.tag
        run_command(compare_command(args, case, out_dir, smooth=False), out_dir / "run_all.log", args.dry_run)
        if not args.skip_smooth:
            smooth_dir = args.out_root / f"{case.tag}_smooth"
            run_command(compare_command(args, case, smooth_dir, smooth=True), smooth_dir / "plot_smooth.log", args.dry_run)

    if not args.dry_run:
        print(write_combined_summary(args))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
